### ISSUE TITLE
names and namespace collisions

### ISSUE THREAD

**Issue by richardsc** [aitap/cmocean#2]
I'm just pulling from our email thread on discussions about this great new package, where @dankelley said:
```
An option that will likely be of least surprise to users would be to name as e.g. diff.colors().  I say this because a user who types

?colors

will see docs for several functions with names ending in ".colors", which means that many users will expect to see ".colors" at the end of functions of this variety.

My preferred way, however, would be to let the user type e.g.

library(cmocean)
image(..., col=cmocean("vorticity"))

to draw a vorticity image with the default version of the vorticity colormap, or maybe

image(..., col=cmocean("vorticity", 1))

for version 1, or

image(..., col=cmocean("vorticity", "2019-04-12"))

for the version on a certain date. The scheme for this is function-returning-function is in lines 2304:2315 of oce R/oce.R ("develop" branch).
```

**Comment by richardsc** [comment]
I like both the `.colors()` idea, and the `cmocean("color")` interface. Maybe we can try a preliminary test of both (for just a function or two) to see what *feels* best.

I do agree that colliding with `diff` will cause me a lot of problems.

**Comment by aitap** [comment]
I agree that once a package is published on CRAN, the maintainer has to worry about backward compatibility, so a good interface has to be worked out before that.

Here is a [branch](https://github.com/aitap/cmocean/tree/single-function) that implements a function-returning-function interface. I hope I understood the suggestion correctly: `cmocean('thermal')` itself returns another function that accepts an integer and returns the specified number of colors. `cmocean` also accepts optional clipping parameters in case someone needs them.

Versioning (#1) is yet to be implemented, though.

**Comment by dankelley** [comment]
This "feels right" to me, e.g. the screenshot.
<img width="1080" alt="Screen Shot 2019-04-12 at 6 49 10 PM" src="https://user-images.githubusercontent.com/99469/56068044-bc0abd80-5d53-11e9-98a0-d9e9914ff2e3.png">

**Comment by richardsc** [comment]
I agree -- that's a nice interface for only slightly more typing:
![image](https://user-images.githubusercontent.com/233584/56072418-fdf42d80-5d6c-11e9-8a7b-1643c1216ee3.png)
