### ISSUE TITLE
add vignette?

### ISSUE THREAD

**Issue by richardsc** [aitap/cmocean#3]
I'm a big believer in vignettes, and I think it would be awesome to have one for this package. Again, some discussion from the email thread. Again, quoting @dankelley:

> This is a tricky one, because I think CRAN may insist that it can rebuild vignettes, which means downloading data will be a problem.  I am not really sure on the prebuilding aspect. I think that in past times, they wanted authors to create the completed vignette (often in .pdf format) but now they want to have authors provide Rmd files. The advantage of this Rmd method is that then CRAN (and users) will be less likely to run into documentation that is at odds with code.  But I don’t think they will want large downloads, and the package may get rejected if a download fails.

> Frankly, I think it would be fine to just show colourbars, like in the cmocean website.  More beautiful real-world images might be pre-built and included as PNGs.  But, to be honest, I would vote on sticking to just the colourbars, and I’d write text suggesting that people consult some of Kristen’s papers for details and more examples.  I think all users would enjoy that reading that material.

I think just showing the colorbars is perfect for a start, but I also like the idea of including some real examples. Of course, for a package like this it makes sense to keep the dependencies minimal (ideally none).

What about including some small datasets with the package that could be used for the vignette? Maybe a text version of the levitus SST/SSS, a WOCE section, etc.

**Comment by richardsc** [comment]
I just banged some stuff into the empty Rmd you made. I'll make a PR.

**Comment by richardsc** [comment]
Oh, and I did it on the `single-function` branch (since I'm really liking that interface).

**Comment by richardsc** [comment]
PR is here: #4

**Comment by aitap** [comment]
Merged #4, thanks!
